### ISSUE TITLE
NoMethodError: [!] undefined method `[]' for nil:NilClass (Sign-in Challenge)

### ISSUE THREAD

**Issue by pmogollons** [tkohout/fastlane-firebase-plugin#6]
Hi,

Im having an issue when running any command from firebase-plugin, we get

```
NoMethodError: [!] undefined method `[]' for nil:NilClass
```
This is happening when the sign-in challenge is triggered, the Capcha is running ok, but sign-in challenge throws this error.

We are running
ruby 2.4.2
firebase-plugin 0.2.1
fastlane 2.62.1

```bash
NoMethodError: [!] undefined method `[]' for nil:NilClass
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/lib/api.rb:127:in `signin_challenge'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/lib/api.rb:60:in `login'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/lib/api.rb:26:in `initialize'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/lib/manager.rb:19:in `new'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/lib/manager.rb:19:in `login'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-firebase-0.2.1/lib/fastlane/plugin/firebase/actions/firebase_list_action.rb:9:in `run'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:33:in `block (2 levels) in parsing_binding'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/admin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.62.1/bin/fastlane:20:in `<top (required)>'
  /Users/admin/.rbenv/versions/2.4.2/bin/fastlane:23:in `load'
  /Users/admin/.rbenv/versions/2.4.2/bin/fastlane:23:in `<top (required)>'
```

**Comment by tkohout** [comment]
Hello, 
what kind of sign in are you using with your account?
